/// Generated by AssetsRefGenerator on 2021/09/07
class Res {
  static const String action = "assets/images/action.png";
  static const String batman = "assets/images/batman.jpg";
  static const String bezier = "assets/images/bezier.png";
  static const String canvas = "assets/images/canvas.png";
  static const String maps = "assets/images/maps.png";
  static const String paint = "assets/images/paint.png";
}
