/// Generated by AssetsRefGenerator on 2021/09/10
class Res {
  static const String action = "assets/images/action.png";
  static const String background = "assets/images/background.png";
  static const String background_s = "assets/images/background_s.png";
  static const String batman = "assets/images/batman.jpg";
  static const String bezier = "assets/images/bezier.png";
  static const String canvas = "assets/images/canvas.png";
  static const String choice = "assets/images/choice.png";
  static const String choice_s = "assets/images/choice_s.png";
  static const String maps = "assets/images/maps.png";
  static const String paint = "assets/images/paint.png";
  static const String pen = "assets/images/pen.png";
  static const String pen_s = "assets/images/pen_s.png";
  static const String recovery = "assets/images/recovery.png";
  static const String recovery_s = "assets/images/recovery_s.png";
  static const String revoke = "assets/images/revoke.png";
  static const String revoke_s = "assets/images/revoke_s.png";
  static const String rubber = "assets/images/rubber.png";
  static const String rubber_s = "assets/images/rubber_s.png";
  static const String screen_shot = "assets/images/screen_shot.png";
  static const String screen_shot_s = "assets/images/screen_shot_s.png";
  static const String shape = "assets/images/shape.png";
  static const String shape_s = "assets/images/shape_s.png";
}
